title : Lucky Blog
tagline: Blog Tagline
author :
  name : Ruoqi Deng
  email : drqzju@gmail.com
  github : luckydrq
  twitter : luckydrq
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
